### Fake News Detection

In [46]:
import numpy as np
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [47]:
df_fake = pd.read_csv("fake.csv")
df_true = pd.read_csv("true.csv")

In [48]:
df_fake.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject      date label  
0  Donald Trump just couldn t wish all Americans ...    News  31/12/17  Fake  
1  House Intelligence Committee Chairman Devin Nu...    News  31/12/17  Fake  
2  On Friday, it was revealed that former Milwauk...    News  30/12/17  Fake  
3  On Christmas day, Donald Trump announced that ...    News  29/12/17  Fake  
4  Pope Francis used his annual Christmas Day mes...    News  25/12/17  Fake  
5  The number of cases of cops brutalizing and ki...    News  25/12/17  Fake  
6  Donald Trump spent a good portion of his day a...    News  23/12/17  Fake  
7  In the wake of yet another court decision that...    News  23/12/17  Fake  
8  Many people have raised the alarm regarding th...    News  22/12/17  Fake  
9  Just when you might have thought we d get a br...    News  21/12/17  Fake

In [49]:
df_true.head(10)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   
5  White House, Congress prepare for talks on spe...   
6  Trump says Russia probe will be fair, but time...   
7  Factbox: Trump on Twitter (Dec 29) - Approval ...   
8         Trump on Twitter (Dec 28) - Global Warming   
9  Alabama official to certify Senator-elect Jone...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
5  WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...  politicsNews   
6  WEST PALM BEACH, Fla (Reuters) - President Don...  politicsNews   
7  The following statements were posted to the ve...  politicsNews   
8  The following statements were posted to the ve...  politicsNews   
9  WASHINGTON (Reuters) - Alabama Secretary of St...  politicsNews   

         date label  
0  12/31/2017  Real  
1    1/1/2018  Real  
2    1/2/2018  Real  
3    1/3/2018  Real  
4    1/4/2018  Real  
5    1/5/2018  Real  
6    1/6/2018  Real  
7    1/7/2018  Real  
8    1/8/2018  Real  
9    1/9/2018  Real

In [50]:
df_fake.shape,df_true.shape

((23378, 5), (21417, 5))

### Now Shuffle the Data

In [51]:
df_merge = pd.concat([df_fake,df_true],axis=0)
df_merge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject      date label  
0  Donald Trump just couldn t wish all Americans ...    News  31/12/17  Fake  
1  House Intelligence Committee Chairman Devin Nu...    News  31/12/17  Fake  
2  On Friday, it was revealed that former Milwauk...    News  30/12/17  Fake  
3  On Christmas day, Donald Trump announced that ...    News  29/12/17  Fake  
4  Pope Francis used his annual Christmas Day mes...    News  25/12/17  Fake  
5  The number of cases of cops brutalizing and ki...    News  25/12/17  Fake  
6  Donald Trump spent a good portion of his day a...    News  23/12/17  Fake  
7  In the wake of yet another court decision that...    News  23/12/17  Fake  
8  Many people have raised the alarm regarding th...    News  22/12/17  Fake  
9  Just when you might have thought we d get a br...    News  21/12/17  Fake

### Now Check the Null Values in the Data set

In [56]:
df.isnull().sum()

text       0
subject    0
label      0
dtype: int64

In [57]:
df.dropna(inplace= True)

In [52]:
df=df_merge.drop(["title","date"],axis=1)
df.head()


text subject label
0  Donald Trump just couldn t wish all Americans ...    News  Fake
1  House Intelligence Committee Chairman Devin Nu...    News  Fake
2  On Friday, it was revealed that former Milwauk...    News  Fake
3  On Christmas day, Donald Trump announced that ...    News  Fake
4  Pope Francis used his annual Christmas Day mes...    News  Fake

In [58]:
df =df.sample(frac=1)

In [59]:
df.head(10)

text       subject label
10535  MILWAUKEE (Reuters) - President Barack Obama s...  politicsNews  Real
16762  TOKYO (Reuters) - A rapidly weakening typhoon ...     worldnews  Real
4977   (Reuters) - Highlights of the day for U.S. Pre...  politicsNews  Real
16261  MOSCOW (Reuters) - An official document seen b...     worldnews  Real
18829  TOKYO (Reuters) - A fledgling party led by pop...     worldnews  Real
10966  NEW YORK (Reuters) - New York City Mayor Bill ...  politicsNews  Real
6675   NEW YORK (Reuters) - Huma Abedin, the longtime...  politicsNews  Real
1659   Donald Trump is quickly closing in on his firs...          News  Fake
11033  DES MOINES, Iowa (Reuters) - The long and some...  politicsNews  Real
21187  Because everyone deserves a  safe space right?...     left-news  Fake

In [60]:
labels = df.label

In [113]:
labels.head(10)

10535    Real
16762    Real
4977     Real
16261    Real
18829    Real
10966    Real
6675     Real
1659     Fake
11033    Real
21187    Fake
Name: label, dtype: object

In [62]:
x_train,x_test,y_train,y_test=train_test_split(df['text'], labels, test_size=0.2, random_state=20)

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier

In [64]:
x_train.head()

10615    WASHINGTON (Reuters) - A former finance co-cha...
9778     Steven Crowder is an amazing and ALWAYS unafra...
4934     NASHVILLE, Tenn. (Reuters) - U.S. President Do...
10207    The slippery slope continues College Park is j...
14863    How can it possibly be legal for these terrori...
Name: text, dtype: object

In [65]:
# initilise a tfidvectorizer
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)

In [66]:
# fit and transform
tfidf_train=tfidf_vectorizer.fit_transform(x_train) 
tfidf_test=tfidf_vectorizer.transform(x_test)

### Passive Aggressive Classifier

In [67]:
#DataFlair - Initialize a PassiveAggressiveClassifier
pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)

PassiveAggressiveClassifier(max_iter=50)

In [68]:
#DataFlair - Predict on the test set and calculate accuracy
y_pred=pac.predict(tfidf_test)
score=accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 99.37%


In [90]:
#DataFlair - Build confusion matrix
confusion_matrix(y_test, y_pred,labels=['Fake','Real'])


array([[4663,   48],
       [  47, 4194]], dtype=int64)

### Logistic Regression

In [96]:
from sklearn.linear_model import LogisticRegression

In [97]:
lr = LogisticRegression()
lr.fit(tfidf_train, y_train)

C:\Users\gaurav\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [98]:
lr.score(tfidf_test,y_test)

0.9886148007590133

In [101]:
y_pred = lr.predict(tfidf_test)

In [102]:
score1=accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 98.86%


In [103]:
cnf_matrix1 = confusion_matrix(y_test, y_pred,)
cnf_matrix1

array([[4663,   48,    0],
       [  47, 4194,    0],
       [   0,    7,    0]], dtype=int64)

### Decision Tree Classifier

In [73]:
from sklearn.tree import DecisionTreeClassifier

In [76]:
dtc = DecisionTreeClassifier()
dtc.fit(tfidf_train, y_train)

DecisionTreeClassifier()

In [75]:
dtc.score(tfidf_test,y_test)

0.9946422591807121

In [104]:
y_pred = dtc.predict(tfidf_test)

In [105]:
score=accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 99.51%


In [106]:
cnf_matrix = confusion_matrix(y_test, y_pred,)
cnf_matrix

array([[4698,   13,    0],
       [  19, 4217,    5],
       [   1,    6,    0]], dtype=int64)

### Random Forest Classifier

In [107]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(tfidf_train, y_train)

RandomForestClassifier()

In [109]:
y_pred = rfc.predict(tfidf_test)

In [110]:
score=accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 99.29%


In [111]:
cnf_matrix = confusion_matrix(y_test, y_pred,)
cnf_matrix

array([[4678,   33,    0],
       [  24, 4217,    0],
       [   0,    7,    0]], dtype=int64)